### PR TITLE
Update Members.md

### PR DESCRIPTION
**Pull request by kenbloom**
Replace David Swanson with Ken Bloom as HCC representative, add David to list of former members.

### CODE REVIEW

**Review by osg-cat — COMMENTED** [review]
Last I checked, Frank did not want to move David to the list of former members until a new (interim) Council Chair had been selected. Is that done yet?

**Review by kenbloom — COMMENTED** [review]
OK, I do see the problem here -- I should not be listed as chair.  But I should be listed as the HCC representative.  Hmm, I don't know Git well enough to go and revise the change I submitted....

**Comment by osg-cat** [comment]
I don’t either, and I’m out sick today. How about I reject this PR and just take care of things once the dust has settled a little more? I don’t think anyone questions your inclusion on the Council.

**Comment by djw8605** [comment]
I made the change.  In the end, since we are not moving David to former yet, the change is just adding Ken as HCC rep.

**Comment by kenbloom** [comment]
I have a cold too!  It's true that it's not urgent although it would be helpful to have this before the Council meeting next week.

**Review by osg-cat — APPROVED** [review]

**Pull request merged**
